{
 "title": "serenity · DMs",
 "tags": [ "serenity" ],
 "time": { "from": "now-6d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "DMs",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 4, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "{ name = \"handle_message\" && (span.guild_name = \"DM\" || span.guild_id = \"0\" || span.guild_id = \"None\") && span.author != \"1211325231659089920\" } | count_over_time()"
    }
   ]
  },
  {
   "title": "DMs per hour",
   "type": "timeseries",
   "gridPos": { "x": 4, "y": 0, "w": 20, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "{ name = \"handle_message\" && (span.guild_name = \"DM\" || span.guild_id = \"0\" || span.guild_id = \"None\") && span.author != \"1211325231659089920\" } | count_over_time()"
    }
   ]
  },
  {
   "title": "Most active users",
   "type": "table",
   "gridPos": { "x": 0, "y": 5, "w": 8, "h": 9 },
   "targets": [
    {
     "query": "{ name = \"handle_message\" && (span.guild_name = \"DM\" || span.guild_id = \"0\" || span.guild_id = \"None\") && span.author != \"1211325231659089920\" && span.author_name != nil } | count_over_time() by (span.author_name)"
    },
    {
     "query": "{ name = \"handle_message\" && (span.guild_name = \"DM\" || span.guild_id = \"0\" || span.guild_id = \"None\") && span.author != \"1211325231659089920\" && span.guild_id =~ \"Some.*\" } | count_over_time() by (span.author)"
    }
   ]
  },
  {
   "title": "Recent DMs",
   "type": "table",
   "gridPos": { "x": 8, "y": 5, "w": 16, "h": 9 },
   "targets": [
    {
     "query": "{ (span.guild_name = \"DM\" || span.guild_id = \"0\" || span.guild_id = \"None\") && span.author != \"1211325231659089920\" } | select(span.content, span.author, span.author_name, span.channel_id, span.attachments, span.links)",
     "limit": 100,
     "spss": 5,
     "tableType": "spans"
    }
   ]
  }
 ]
}