{
 "title": "serenity · guild",
 "tags": [ "serenity" ],
 "time": { "from": "now-6d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "guild", "label": "Guild (name, id or regex)", "query": ".*" }
  ]
 },
 "panels": [
  {
   "title": "Messages",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 4, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "{ name = \"handle_message\" && (span.guild_name =~ \"$guild\" || span.guild_id =~ \".*$guild.*\") } | count_over_time()"
    }
   ]
  },
  {
   "title": "Messages per hour",
   "type": "timeseries",
   "gridPos": { "x": 4, "y": 0, "w": 20, "h": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "{ name = \"handle_message\" && (span.guild_name =~ \"$guild\" || span.guild_id =~ \".*$guild.*\") } | count_over_time()"
    }
   ]
  },
  {
   "title": "Most active users",
   "type": "table",
   "gridPos": { "x": 0, "y": 5, "w": 12, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "{ name = \"handle_message\" && (span.guild_name =~ \"$guild\" || span.guild_id =~ \".*$guild.*\") && span.author_name != nil } | count_over_time() by (span.author_name)"
    },
    {
     "query": "{ name = \"handle_message\" && (span.guild_name =~ \"$guild\" || span.guild_id =~ \".*$guild.*\") && span.guild_id =~ \"Some.*\" } | count_over_time() by (span.author)"
    }
   ]
  },
  {
   "title": "Channels",
   "type": "table",
   "gridPos": { "x": 12, "y": 5, "w": 12, "h": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "{ name = \"handle_message\" && (span.guild_name =~ \"$guild\" || span.guild_id =~ \".*$guild.*\") && span.channel_id != nil } | count_over_time() by (span.channel_id)"
    }
   ]
  },
  {
   "title": "Recent activity",
   "type": "table",
   "gridPos": { "x": 0, "y": 14, "w": 24, "h": 13 },
   "targets": [
    {
     "query": "{ (span.guild_name =~ \"$guild\" || span.guild_id =~ \".*$guild.*\") } | select(span.content, span.author, span.author_name, span.channel_id, span.attachments, span.links)",
     "limit": 100,
     "spss": 5,
     "tableType": "spans"
    }
   ]
  }
 ]
}