# ==============================================================================
# Caddy — TLS terminator
# ==============================================================================
# Caddy does NOT manage certificates. security.acme issues them and caddy reads
# the directory read-only, which is why the global block is empty and every site
# names its files explicitly: a `tls <cert> <key>` directive turns off
# certificate management for that site.
#
# Upstreams are container names, resolved by docker's embedded DNS on the proxy
# network. Nothing here is an IP address, so a container can be recreated with a
# new address and caddy is none the wiser.
{
  config,
  lib,
  pkgs,
  ...
}:

let
  inherit (config.infra) domain proxyNetwork;

  # Same number for the uid and the gid, from modules/ids.nix.
  id = toString config.infra.serviceId.caddy;

  # The certificate directory as caddy sees it. NixOS names the private key
  # key.pem, NOT privkey.pem as certbot did — pointing at the wrong name here
  # fails the whole config load, so it is at least loud.
  certDir = "/etc/caddy/certs";

  sites = [
    {
      host = "music.${domain}";
      upstream = "navidrome:4533";
    }
    {
      host = "mail.${domain}";
      upstream = "webmail:80";
    }
    {
      host = "git.${domain}";
      upstream = "forgejo:4242";
    }
    {
      host = "status.${domain}";
      upstream = "kuma:3001";
    }
  ];

  # Tabs and this exact shape are what `caddy fmt` produces, so `caddy validate`
  # on the generated file is clean rather than warning about formatting every
  # time someone checks it.
  caddyfile = pkgs.writeText "Caddyfile" (
    lib.concatStringsSep "\n" (
      [
        "# Generated by Nix — edit modules/containers/caddy.nix"
        "{"
        "\t# Certificates come from security.acme on the host."
        "\t# See the `tls` directive on each site below."
        "\t admin off"
        "}"
      ]
      ++ lib.concatMap (site: [
        ""
        "${site.host} {"
        "\ttls ${certDir}/fullchain.pem ${certDir}/key.pem"
        "\treverse_proxy ${site.upstream}"
        "}"
      ]) sites
    )
    + "\n"
  );
in
{
  virtualisation.oci-containers.containers.caddy = {
    image = "caddy:2.11.4-alpine";

    ports = [
      "80:80"
      "443:443"
      # HTTP/3. The nftables input chain has to allow udp 443 for this to be
      # more than decoration.
      "443:443/udp"
    ];

    volumes = [
      "${caddyfile}:/etc/caddy/Caddyfile:ro"
      "/var/lib/acme/${domain}:${certDir}:ro"
    ];

    networks = [ proxyNetwork ];

    extraOptions = [
      # Not root. The certificate directory is group-owned by `caddy` (see
      # modules/acme.nix), so this account reads exactly those files and
      # nothing else on the host.
      "--user=${id}:${id}"

      "--read-only"
      "--security-opt=no-new-privileges:true"

      # NET_BIND_SERVICE is NOT for binding: docker sets
      # net.ipv4.ip_unprivileged_port_start=0, so any uid may bind 80 and 443.
      # It is here because /usr/bin/caddy carries a file capability, and the
      # kernel refuses to exec such a binary when the bounding set is empty —
      # `--cap-drop=ALL` alone fails with "exec: operation not permitted"
      # before caddy runs at all.
      "--cap-drop=ALL"
      "--cap-add=NET_BIND_SERVICE"

      # /data and /config were named volumes, which a non-root container cannot
      # write because docker creates them root-owned. They are ephemeral here
      # instead: with certificates supplied by acme and the admin API off, that
      # storage holds OCSP staples and an autosave, both re-derived on start.
      # uid/gid rather than mode=1777, so nothing in the container is
      # world-writable.
      "--tmpfs=/tmp:rw,noexec,nosuid,nodev,size=16m,uid=${id},gid=${id},mode=0700"
      "--tmpfs=/data:rw,nosuid,nodev,size=16m,uid=${id},gid=${id},mode=0700"
      "--tmpfs=/config:rw,nosuid,nodev,size=4m,uid=${id},gid=${id},mode=0700"
    ];
  };

  # acme writes the certificate before anything can serve it. Without this a
  # first boot starts caddy against an empty directory and it exits.
  systemd.services.docker-caddy = {
    after = [ "acme-${domain}.service" ];
    wants = [ "acme-${domain}.service" ];
  };
}
