# ==============================================================================
# Caddy — TLS terminator
# ==============================================================================
# Caddy does NOT manage certificates. security.acme issues them and caddy reads
# the directory read-only, which is why the global block is empty and every site
# names its files explicitly: a `tls <cert> <key>` directive turns off
# certificate management for that site.
#
# Upstreams are container names, resolved by docker's embedded DNS on the proxy
# network. Nothing here is an IP address, so a container can be recreated with a
# new address and caddy is none the wiser.
{
  config,
  lib,
  pkgs,
  ...
}:

let
  inherit (config.infra) domain proxyNetwork;

  # The certificate directory as caddy sees it. NixOS names the private key
  # key.pem, NOT privkey.pem as certbot did — pointing at the wrong name here
  # fails the whole config load, so it is at least loud.
  certDir = "/etc/caddy/certs";

  sites = [
    {
      host = "music.${domain}";
      upstream = "navidrome:4533";
    }
    {
      host = "mail.${domain}";
      upstream = "webmail:80";
    }
    {
      host = "git.${domain}";
      upstream = "forgejo:4242";
    }
    {
      host = "status.${domain}";
      upstream = "kuma:3001";
    }
  ];

  # Tabs and this exact shape are what `caddy fmt` produces, so `caddy validate`
  # on the generated file is clean rather than warning about formatting every
  # time someone checks it.
  caddyfile = pkgs.writeText "Caddyfile" (
    lib.concatStringsSep "\n" (
      [
        "# Generated by Nix — edit modules/containers/caddy.nix"
        "{"
        "\t# Deliberately empty: certificates come from security.acme on the host."
        "\t# See the `tls` directive on each site below."
        "}"
      ]
      ++ lib.concatMap (site: [
        ""
        "${site.host} {"
        "\ttls ${certDir}/fullchain.pem ${certDir}/key.pem"
        "\treverse_proxy ${site.upstream}"
        "}"
      ]) sites
    )
    + "\n"
  );
in
{
  virtualisation.oci-containers.containers.caddy = {
    image = "caddy:2.11.4-alpine";

    ports = [
      "80:80"
      "443:443"
      # HTTP/3. The nftables input chain has to allow udp 443 for this to be
      # more than decoration.
      "443:443/udp"
    ];

    volumes = [
      "${caddyfile}:/etc/caddy/Caddyfile:ro"
      "/var/lib/acme/${domain}:${certDir}:ro"
      "caddy_data:/data"
      "caddy_config:/config"
    ];

    networks = [ proxyNetwork ];
  };

  # acme writes the certificate before anything can serve it. Without this a
  # first boot starts caddy against an empty directory and it exits.
  systemd.services.docker-caddy = {
    after = [ "acme-${domain}.service" ];
    wants = [ "acme-${domain}.service" ];
  };
}
