keys:
  - &primary age1hxd7xtvy5e52pe9d8x2p7g6yls0zmsp668p0rvu0qw02dd7dryuqrvuq7h
  - &backup age1twlfuf88nxhdevt070c3yrklljm0xc0jpyut0722av342ux4tqzqtl3mpz
creation_rules:
  - path_regex: secrets\.yaml$
    key_groups:
      - age:
          - *primary
          - *backup
