keys:
  - &hutao age1twlfuf88nxhdevt070c3yrklljm0xc0jpyut0722av342ux4tqzqtl3mpz
  - &nixos age1wa7049wzlytz0rc3psfj8vynwrjfjud9y0p7p8v80vzemdwjudgqcejyav
creation_rules:
  - path_regex: secrets\.yaml$
    key_groups:
      - age: [*hutao, *nixos]
