{
  imports = [
    ./modules/options.nix
    ./modules/ids.nix
    ./modules/secrets.nix
    ./modules/services.nix
    ./modules/boot.nix
    ./modules/hardware.nix
    ./modules/nix.nix
    ./modules/users.nix
    ./modules/networking.nix
    ./modules/firewall.nix
    ./modules/security.nix
    ./modules/acme.nix
    ./modules/postgres.nix
    ./modules/backups.nix
    ./modules/image-archive.nix
    ./modules/renovate.nix
    ./modules/pages-pull.nix
    ./modules/pages-hook.nix
    ./modules/syncthing.nix
    ./modules/containers
  ];
}
